apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 15
      - pause: {}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: custom-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: custom-index
        configMap:
          name: nginx-index
  revisionHistoryLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <html>
    <head><title>Custom Page</title></head>
    <body>
      <h1>Welcome to the Custom Nginx Page!</h1>
    </body>
    </html>
